function fromKey(k) { return new Date(k + 'T00:00:00'); }
function formatDate(k) {
  return fromKey(k).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
}
function safeName(name) {
  return (name ?? 'trip').replace(/[^a-z0-9]/gi, '_').toLowerCase();
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportMarkdown(trip) {
  const { name, destination, startDate, endDate, itinerary } = trip;
  const lines = [];

  lines.push(`# ${name}`);
  lines.push(`**${destination?.city}, ${destination?.country}** · ${formatDate(startDate)} → ${formatDate(endDate)}`);
  lines.push('');

  if (itinerary?.totalBudget) {
    lines.push(`> Estimated total budget: ~$${itinerary.totalBudget}`);
    lines.push('');
  }

  if (itinerary?.generalTips?.length) {
    lines.push('## General Tips');
    itinerary.generalTips.forEach(tip => lines.push(`- ${tip}`));
    lines.push('');
  }

  for (const day of (itinerary?.days ?? [])) {
    lines.push(`## Day ${day.day} — ${formatDate(day.date)}: ${day.title}`);
    if (day.daySummary) lines.push(`_${day.daySummary}_`);
    lines.push('');

    for (const act of (day.activities ?? [])) {
      const timePrefix = act.time ? `${act.time} — ` : '';
      lines.push(`### ${timePrefix}${act.title}`);
      if (act.description) lines.push(act.description);
      const meta = [
        act.duration  && `Duration: ${act.duration}`,
        act.transport && `Transport: ${act.transport}`,
        act.cost      && `Cost: ${act.cost}`,
      ].filter(Boolean);
      if (meta.length) lines.push(meta.join(' · '));
      if (act.tip) lines.push(`> Tip: ${act.tip}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by TRVLTOO*');

  triggerDownload(
    new Blob([lines.join('\n')], { type: 'text/markdown' }),
    `${safeName(name)}.md`,
  );
}

export function exportJSON(trip) {
  const data = {
    name: trip.name,
    destination: trip.destination,
    startDate: trip.startDate,
    endDate: trip.endDate,
    itinerary: trip.itinerary,
    exportedAt: new Date().toISOString(),
    source: 'trvltoo',
  };
  triggerDownload(
    new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }),
    `${safeName(trip.name)}.json`,
  );
}

export async function exportPDF(trip) {
  const { jsPDF } = await import('jspdf');
  const { name, destination, startDate, endDate, itinerary } = trip;
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const MARGIN = 20;
  const PAGE_W = 210;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  let y = MARGIN;

  // Dark background
  pdf.setFillColor(15, 23, 42);
  pdf.rect(0, 0, PAGE_W, 297, 'F');

  function addText(text, { fontSize = 11, weight = 'normal', color = [220, 220, 220], gap = 3, x = MARGIN } = {}) {
    pdf.setFontSize(fontSize);
    pdf.setTextColor(...color);
    pdf.setFont('helvetica', weight);
    const lines = pdf.splitTextToSize(String(text), CONTENT_W);
    const lineH = fontSize * 0.42;
    if (y + lines.length * lineH > 280) {
      pdf.addPage();
      pdf.setFillColor(15, 23, 42);
      pdf.rect(0, 0, PAGE_W, 297, 'F');
      y = MARGIN;
    }
    pdf.text(lines, x, y);
    y += lines.length * lineH + gap;
  }

  function rule() {
    pdf.setDrawColor(20, 184, 166, 0.4);
    pdf.setLineWidth(0.3);
    pdf.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 5;
  }

  // Header
  addText('TRVLTOO', { fontSize: 8, weight: 'bold', color: [20, 184, 166], gap: 3 });
  addText(name, { fontSize: 20, weight: 'bolditalic', color: [255, 255, 255], gap: 3 });
  addText(`${destination?.city}, ${destination?.country}`, { fontSize: 11, color: [160, 160, 160], gap: 2 });
  addText(`${formatDate(startDate)} → ${formatDate(endDate)}`, { fontSize: 9, color: [100, 120, 130], gap: 2 });
  if (itinerary?.totalBudget) {
    addText(`Est. total ~$${itinerary.totalBudget}`, { fontSize: 9, color: [20, 184, 166], gap: 4 });
  }
  rule();

  // General tips
  if (itinerary?.generalTips?.length) {
    addText('General Tips', { fontSize: 10, weight: 'bold', color: [200, 200, 200], gap: 2 });
    itinerary.generalTips.forEach(tip => addText(`• ${tip}`, { fontSize: 9, color: [140, 140, 140], gap: 1.5 }));
    y += 3;
    rule();
  }

  // Days
  for (const day of (itinerary?.days ?? [])) {
    addText(`Day ${day.day}  ·  ${day.title}`, { fontSize: 12, weight: 'bolditalic', color: [255, 255, 255], gap: 1 });
    addText(formatDate(day.date), { fontSize: 8, color: [20, 184, 166], gap: day.daySummary ? 2 : 4 });
    if (day.daySummary) addText(day.daySummary, { fontSize: 9, weight: 'italic', color: [130, 130, 130], gap: 4 });

    for (const act of (day.activities ?? [])) {
      const timePrefix = act.time ? `${act.time}  ` : '';
      addText(`${timePrefix}${act.title}`, { fontSize: 10, weight: 'bold', color: [210, 210, 210], gap: 1 });
      if (act.description) addText(act.description, { fontSize: 8, color: [120, 120, 120], gap: 1 });
      const meta = [act.duration, act.transport, act.cost].filter(Boolean).join(' · ');
      if (meta) addText(meta, { fontSize: 8, color: [90, 90, 100], gap: 1 });
      if (act.tip) addText(`Tip: ${act.tip}`, { fontSize: 8, weight: 'italic', color: [200, 160, 40], gap: 3 });
    }
    y += 2;
  }

  rule();
  addText('Generated by TRVLTOO', { fontSize: 7, color: [50, 70, 90], gap: 0 });

  pdf.save(`${safeName(name)}.pdf`);
}
