-- ============================================================
-- TRVLTOO — Trips & Shared Itineraries
-- ============================================================

-- 1. Trips table — persists every generated itinerary per user
create table if not exists public.trips (
  id            uuid primary key default gen_random_uuid(),
  user_id       text not null,
  destination   text not null,
  arrival_date  date not null,
  persona       text not null,
  budget        text not null check (budget in ('$', '$$', '$$$')),
  energy        smallint not null check (energy between 1 and 10),
  picks_snapshot jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

-- 2. Shared itineraries — publicly readable, owner-writable
create table if not exists public.shared_itineraries (
  id            uuid primary key default gen_random_uuid(),
  user_id       text not null,
  destination   text not null,
  arrival_date  date not null,
  persona       text not null,
  budget        text not null,
  picks_snapshot jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

-- 3. Row Level Security
alter table public.trips enable row level security;
alter table public.shared_itineraries enable row level security;

-- trips: users only see and modify their own rows
create policy "trips_select_own"   on public.trips for select using (auth.uid()::text = user_id);
create policy "trips_insert_own"   on public.trips for insert with check (auth.uid()::text = user_id);
create policy "trips_delete_own"   on public.trips for delete using (auth.uid()::text = user_id);

-- shared itineraries: anyone can read, owner can write
create policy "shared_select_all"  on public.shared_itineraries for select using (true);
create policy "shared_insert_own"  on public.shared_itineraries for insert with check (auth.uid()::text = user_id);
create policy "shared_delete_own"  on public.shared_itineraries for delete using (auth.uid()::text = user_id);

-- 4. Indexes for common query patterns (Audit item #6)
create index if not exists idx_trips_user_id
  on public.trips (user_id);

create index if not exists idx_trips_destination
  on public.trips (destination);

create index if not exists idx_trips_user_created
  on public.trips (user_id, created_at desc);

create index if not exists idx_shared_id
  on public.shared_itineraries (id);

-- 5. Comments
comment on table public.trips is 'Every itinerary generated by an authenticated user.';
comment on table public.shared_itineraries is 'Publicly shareable copies of itineraries.';
